namespace Packt.Shared;

//this file simulates an autogenerated class

public partial class Person : object {
  public string Origin{
    get{
      return string.Format(
        "{0} was born on {1}.",
        arg0: Name,
        arg1: HomePlanet
      );
    }
  }

  public string Greeting => $"{Name} says \"Hello!\"";
  public int Age => DateTime.Today.Year - DateOfBirth.Year;

  public string? FavoriteIceCream { get; set; }

  private string? favoritePrimaryColor {
    get {
      return favoritePrimaryColor;
    }
    set{
      switch (value?.ToLower()){
        case "red":
        case "yellow":
        case "blue":
          favoritePrimaryColor = value;
          break;
        default:
          throw new ArgumentException(
            $"{value} is not a primary color. " +
            "Choose from: red, yellow, blue" 
          );
      }
    }
  }
}
