namespace Packt.Shared;

//this file simulates an autogenerated class

public partial class Person : object {
  public string Origin{
    get{
      return string.Format(
        "{0} was born on {1}.",
        arg0: Name,
        arg1: HomePlanet
      );
    }
  }

  public string Greeting => $"{Name} says \"Hello!\"";
  public int Age => DateTime.Today.Year - DateOfBirth.Year;

  public string? FavoriteIceCream { get; set; }

  private string? favoritePrimaryColor;

  public string? FavoritePrimaryColor {
    get {
      return favoritePrimaryColor;
    }
    set{
      favoritePrimaryColor = (value?.ToLower()) switch
      {
        "red" or "yellow" or "blue" => value,
        _ => throw new ArgumentException(
                    $"{value} is not a primary color. " +
                    "Choose from: red, yellow, blue"
                  ),
      };
    }
  }

  public Person this[int index]{
    get{
      return Children[index];
    }
    set {
      Children[index] = value;
    }
  }

  public Person this[string name]{
    get{
      return Children.Find(p => p.Name == name);
    }
    set{
      Person found = Children.Find(p => p.Name == name);
      if(found is not null) found = value;
    }
  }
}
