namespace Packt.Shared;

//this file simulates an autogenerated class

public partial class Person : object {
  public string Origin{
    get{
      return string.Format(
        "{0} was born on {1}.",
        arg0: Name,
        arg1: HomePlanet
      );
    }
  }

  public string Greeting => $"{Name} says \"Hello!\"";
  public int Age => DateTime.Today.Year - DateOfBirth.Year;
}
